name: Test

on:
    push:
        branches:
            - main
            - dev
            - next
    pull_request:
        branches:
            - main
#            - dev
            - next
            - v3

jobs:
    test:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, macos-latest, windows-2019]
                node: [14]
                include:
                    - node: 18
                      os: ubuntu-latest
                      experimental: true
        steps:
            - uses: actions/checkout@v3
              with:
                  # SEE: https://github.com/lerna/lerna/issues/2542
                  fetch-depth: '0'

            - uses: actions/cache@v3
              id: cache
              with:
                  path: |
                      node_modules
                      **/node_modules
                  key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-yarn-

            - name: Use Node.js ${{ matrix.node }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node }}

            - name: Install dependencies
              if: steps.cache.outputs.cache-hit != 'true' || matrix.os == 'windows-2019'
              run: yarn install

            - name: Bootstrap
              run: yarn bootstrap

            - name: Build
              run: yarn build

            - name: Test
              run: yarn test:coverage

            - name: Spell Check
              run: yarn spellcheck
